version: "3.8"
services:
  fastapi-app:
    image: nutanix-converge
    build:
      context: .
    ports:
      - "81:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
