version: "3.8"
services:
  fastapi-app:
    image: nutanix-converge
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # no need for 'command' here, Dockerfile CMD handles it
